config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  post '/rate' => 'rater#create', :as => 'rate'

  root                  'static_pages#home'
  get 'help'         => 'static_pages#help'
  get 'about'        => 'static_pages#about'
  get 'contact'      => 'static_pages#contact'
  get 'marketing'      => 'static_pages#marketing'
  get 'pricing'      => 'static_pages#pricing'
  get 'privacy_policy'  => 'static_pages#privacy_policy'
  get 'terms_of_service' => 'static_pages#terms_of_service'
  get 'register'     => 'facilities#new'

  resources :users do
    resources :facility_roles
    resources :routes do
      member do
        post :quick_flash #output path - expire_route/:id
        post :quick_redpoint #output path - tagged_route/:id
        post :quick_project
        post :quick_tick
        post :route_like
        post :route_unlike
      end
      collection do
        get :filter_results
        get :index
      end
      resources :ticks
    end
    collection do #collection gets index of users rather than specific tick ID
      get :manage_users
    end
    member do
      get :following, :followers, :competitions, :competition, :new_competition
    end
    member do
      post :follow #output path - user/:id/follow
      post :unfollow #output path - user/:id/unfollow
      get :phone #output path - user/:id/phone
    end

    resources :ticks do
      collection do #collection gets index of ticks rather than specific tick ID
        get :tick_list
      end
    end
    resources :facilities do
      post :unfollow_facility
      post :follow_facility #output path - /users/:user_id/facilities/:facility_id/follow_facility(.:format), user_facility_follow_facility
      resources :routes do
        resources :ticks

      end
    end
    member do
      get :inbox
      get :home
      get :analytics
    end
    resources :competitions do
      member do
        post :invite_user
      end
    end
  end

  resources :facility_roles do
    member do
      post :confirm
    end
  end

  resources :leads

  resources :plans
  resources :charges

  post 'admin/subscriptions/webhook'      => 'admin/subscriptions#webhook' #webhook for Stripe

  resources :relationships,       only: [:create, :destroy]

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :grade_systems do
      resources :grades
    end

    resources :facilities do
      resources :routes do

        member do
          post :expire #output path - expire_route/:id
          post :unexpire
          post :tagged #output path - tagged_route/:id
          post :untagged #output path - tagged_route/:id
          post :create_task
          post :expire_zone_show #expire from zone show page
        end
      end
      resources :subscriptions do
        member do
          post :cancel
        end
      end

      member do
        get :plans
        post :choose_free_plan
        post :choose_basic_plan
        post :choose_pro_plan

      end

      resources :grades
      resources :zones do
        post :mass_expire
        post :mass_create_tasks
      end
      resources :walls
      resources :setters # delete after facility_roles is set up
      resources :facility_roles do
        member do
          post :resend_invite
        end
      end
      resources :sub_child_zones
      resources :facility_grade_systems
      resources :facility_targets
      resources :custom_colors
      resources :tasks do
        member do
          post :activate_route #output path - activate_route/:id
          post :complete_task
          post :uncomplete_task
        end
      end
      resources :competitions do
        member do
          get :routes
          get :route_list
          post :add_route
          post :remove_route
        end
        resources :routes do
          post :add_route
          post :remove_route
        end
      end

    end
  end

  resources :facilities do

    resources :routes, only: [:index, :show]
    resources :grades, only: [:index, :show]
    resources :zones, only: [:index, :show]
    resources :walls, only: [:index, :show]
    resources :setters, only: [:index, :show]
    resources :ticks
    resources :facility_roles
    member do
      post :follow_facility
      post :unfollow_facility
    end
    resources :competitions do
      member do
        get :routes
        get :followers
        get :invite
        get :route_list
        get :results
        post :add_route
        post :remove_route
        post :add_user
      end
      resources :routes do
        post :add_route
        post :remove_route
          member do
            post :quick_flash #output path - expire_route/:id
            post :quick_redpoint #output path - tagged_route/:id
            post :quick_project
            post :quick_comp_flash #output path - expire_route/:id
            post :quick_comp_redpoint #output path - tagged_route/:id
            post :quick_comp_project
            post :quick_tick
          end
      end
    end

    member do
      get :followers
      get :social
      get :analytics
    end
  end

  default_url_options :host => 'localhost:3000'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController



  def home
    if user_signed_in?
      if @userfacilities.count > 0 #facilities where role is not climber
        if FacilityRole.where(email: current_user.email, user_id: nil).count > 0 #checks if user has any pending invites
          redirect_to inbox_user_url(current_user) #redirects to root where they will be asked to confirm invite.
        else
          redirect_to home_user_path(current_user)
        end
      else
        if FacilityRole.where(email: current_user.email, user_id: nil).count > 0 #checks if user has any pending invites
          redirect_to inbox_user_url(current_user) #redirects to root where they will be asked to confirm invite.
        else
        redirect_to home_user_path(current_user)
        end
      end
    end
    @user = User.new

    @lead = Lead.new

    @demo_facility = Facility.where(demo: true).first
    @random_number = rand(1..15)
  end

  def help
  end

  def about
  end

  def contact
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_add_route.html.erb
  <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 col-lg-4 col-lg-offset-4">
    <div class="span7 text-center">
      <div class="row">
        <% if @userfacilities.count > 1 %>
        <div class="btn-group btn-homeaction btn-block">
          <button type="button" class="btn btn-homeaction btn-lg btn-block dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Add routes <span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
            <% @userfacilities.each do |f| %>
            <li><%= link_to f.name + " " + f.location, new_admin_facility_route_path(f) %></li>
            <% end %>
          </ul>
        </div>
        <br/>
        <br/>
        <div class="btn-group btn-homeaction  btn-block">
          <button type="button" class="btn btn-homeaction btn-lg btn-block dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Find routes <span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
            <% @userfacilities.each do |f| %>
            <li><%= link_to f.name + " " + f.location, admin_facility_routes_path(f) %></li>
            <% end %>
          </ul>
        </div>

        <% elsif @userfacilities.count == 1 %>
          <%= link_to "ADD ROUTES", new_admin_facility_route_path(@userfacilities.first), class: "btn btn-homeaction btn-lg btn-block" %>
          <%= link_to "FIND ROUTES", admin_facility_routes_path(@userfacilities.first), class: "btn btn-homeaction btn-lg btn-block" %>
        <% else %>
          <%= link_to "Register your facility", new_admin_facility_path, class: "btn btn-submit btn-lg btn-block" %>
        <% end %>

        </div>
    </div>
  </div>

app/views/static_pages/_login_buttons.html.erb
<div class="container-fluid">
  <div class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 col-lg-6 col-lg-offset-3">
    <div class="span7 text-center">
      <div class="row hidden-xs">
        <span><%= button_to "Facebook login", user_facebook_omniauth_authorize_path, class: 'btn btn-facebook btn-sm' %></span>
      </div>
      <div class="row hidden-sm hidden-md hidden-lg hidden-xl">
        <span><%= button_to "Facebook", user_facebook_omniauth_authorize_path, class: 'btn btn-facebook btn-mobile btn-sm' %></span>
      </div>
      <br/>
      <div class="row hidden-xs">
        <span><%= button_to "Google login", user_google_oauth2_omniauth_authorize_path, class: 'btn btn-google btn-sm' %></span>
      </div>
      <div class="row hidden-sm hidden-md hidden-lg hidden-xl">
        <span><%= button_to "Google", user_google_oauth2_omniauth_authorize_path, class: 'btn btn-google btn-mobile btn-sm' %></span>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/_marketing.html.erb
        <div class="row">
          <div class="col-xs-12">
            <h1>START SETTING SMART</h1>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-10 col-sm-11">
            <p><span class="glyphicon glyphicon-cloud"></span><span class="tab"> Manage your route setting program from anywhere </span></p>
          </div>
          <div class="col-xs-2 col-sm-1">
            <p><span class="glyphicon glyphicon-ok glyphicon-green pull-right"></span></p>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-10 col-sm-11">
            <p><span class="glyphicon glyphicon-list-alt"></span><span class="tab"> Visualize your routes in a customized database with unlimited storage</span></p>
          </div>
          <div class="col-xs-2 col-sm-1">
            <p><span class="glyphicon glyphicon-ok glyphicon-green pull-right"></span></p>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-10 col-sm-11">
            <p><span class="glyphicon glyphicon-user"></span><span class="tab"> Invite your team & assign roles and permissions</span></p>
          </div>
          <div class="col-xs-2 col-sm-1">
            <p><span class="glyphicon glyphicon-ok glyphicon-green pull-right"></span></p>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-10 col-sm-11">
            <p><span class="glyphicon glyphicon-tasks"></span><span class="tab"> Set goals and assign tasks</span></p>
          </div>
          <div class="col-xs-2 col-sm-1">
            <p><span class="glyphicon glyphicon-ok glyphicon-green pull-right"></span></p>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-10 col-sm-11">
            <p><span class="glyphicon glyphicon-stats"></span><span class="tab"> Use powerful analytics to manage your facility</span></p>
          </div>
          <div class="col-xs-2 col-sm-1">
            <p><span class="glyphicon glyphicon-ok glyphicon-green pull-right"></span></p>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-10 col-sm-11">
            <p><span class="glyphicon glyphicon-globe"></span><span class="tab"> Customize your grading scale or use standard outdoor systems</span></p>
          </div>
          <div class="col-xs-2 col-sm-1">
            <p><span class="glyphicon glyphicon-ok glyphicon-green pull-right"></span></p>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-10 col-sm-11">
            <p><span class="glyphicon glyphicon-edit"></span><span class="tab"> Document routes based on your specific needs </span></p>
          </div>
          <div class="col-xs-2 col-sm-1">
            <p><span class="glyphicon glyphicon-ok glyphicon-green pull-right"></span></p>
          </div>
        </div>
        <br/>
        <div class="row center">
          <div class="col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
            <%= link_to "Set your first 100 routes for free", new_admin_facility_path, class: "btn btn-save btn-md btn-block" %>
          </div>
        </div>
        <div class="center">$20/month after that.  No commitment.  Cancel anytime. </div>
        <br/>
        <br/>
        <div class="row center">
          <%= image_tag("https://s3-us-west-2.amazonaws.com/climbconnect-assets/backgrounds/cc-displays.jpg" ,width: '60%', height: '60%') %>
        </div>

app/views/static_pages/_route_list.html.erb
<% @demo_facility.routes.includes(:grade, :zone, :wall, :user).current.last(3).each do |f| %>
<ol class="routelist routelist-dark">


    <li>



<div class="list-color-circle", style="background-color: <%= f.color_hex %>"><span class="text"><%= "" %></span></div>

    <%= link_to admin_facility_route_path( f.facility, f) do %>
  <span>
    <div class="container-fluid">
      <div class="row doubletab">
        <div class="col-xs-7">
          <% if params[:facility_id].present? %>
          <h3><strong>
            <% if f.color? %>
              <%= f.grade.grade + " "+ f.color.upcase if f.grade %>
            <% elsif (color_name(f.color_hex,f.facility)).nil? %>
              <%= f.grade.grade if f.grade %>
            <% else %>
              <%= f.grade.grade + " "+ color_name(f.color_hex,f.facility)[0].upcase if f.grade %>
            <% end %>
          </strong></h3>

          <% else %>
          <h3><strong>
            <% if f.color? %>
              <%= f.grade.grade + " "+ f.color.upcase if f.grade %>
            <% elsif (color_name(f.color_hex,f.facility)).nil? %>
              <%= f.grade.grade if f.grade %>
            <% else %>
              <%= f.grade.grade + " "+ color_name(f.color_hex,f.facility)[0].upcase if f.grade %>
            <% end %>
          </strong></h3>
          <% end %>


        </div>
        <div class="col-xs-5">
          <div id="expire_buttons_<%= f.id %>">
          <% if f.active? %>
              <div class="expire-circle">
                <i class="fa fa-flash" aria-hidden="true"></i>
                <span class="text"><%= "active" %></span>
              </div>
          <% else %>

          <div class="expire-circle expired">
            <i class="fa fa-flash" aria-hidden="true"></i>
            <span class="text"><%= "expired" %></span>
          </div>

          <% end %>
          <div class="expire-circle task-circle">
            <i class="fa fa-wrench" aria-hidden="true"></i>
            <span class="text"><%= "task" %></span>
          </div>

          </div>
        </div>

      </div>
      <div class="row doubletab">
        <div class="col-xs-7">
          <h2> <%= f.name if f.name %> <%= "#" + f.id.to_s %></h2>
        </div>
      </div>


      <div class="row">

        <div class="col-sm-12">
            <div><%= f.zone.name if f.zone %> > <%= f.wall.name if f.wall %></div>
        </div>
        <div class="col-xs-12 col-sm-12">
          <div><%= f.user.name if f.user %></div>
        </div>
        <div class="col-xs-12 col-sm-12">

          <% if (f.enddate.present?) && (f.enddate < Date.current) %>
            <i class="fa fa-window-close red" aria-hidden="true"></i> expired <%= f.enddate.strftime("%b %d, %Y") %>
          <% else %>

              <% unless params[:controller] == 'admin/tasks' %>
                <% if (days_ago(f) == "today") %>
                  <span>set <%= days_ago(f) %></span>
                <% else %>
                  set <%= days_ago(f) %> ago
                <% end %>
              <% else %>
                <% if f.setdate? %>
                due on <%= f.setdate.strftime("%b %d, %Y") %>
                <% end %>
              <% end %>
            <% end %>


        </div>
      </div>
    </span>
    <% end %>










  </li>
</ol>
  <% end %>

app/views/static_pages/home.html.erb
<meta name="description" content="Track your indoor climbing today, with Climb Connect!" />
<meta name="keywords" content="routesetting, route setting, climbing, gym climb tracker, gym management" />

<div class="no-margin">
  <script>
  $(document).on('ready turbolinks:load', function(){
     var scroll_start = 0;
     var startchange = $('#startchange');
     var homePage = $('#homePage');
     var offset = startchange.offset();
       if(homePage) {
         $('.navbar2').css('background', 'transparent');
      }
      if (startchange.length){
     $(document).scroll(function() {
        scroll_start = $(this).scrollTop();
        if(homePage && scroll_start > offset.top) {
            $(".navbar2").css('background', 'rgba(0,0,0,.8)');
         } else {
            $('.navbar2').css('background', 'transparent');
         }
     });
      }
  });

  $('#hamburger').click(function() {
      $('.navbar2').css({
          'background': 'rgba(0,0,0,.8)',
      });
  });
  </script>
<div class="home-body">
  <div id="homePage"></div>
  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel" data-interval="50000">


  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <div class="hidden-xs">
      <%= image_tag("https://s3-us-west-2.amazonaws.com/climbconnect-assets/backgrounds/homepage-chalkbag-logo.jpg", alt: "climb connect home background", class: "img-responsive") %>
      </div>
      <div class="hidden-sm hidden-md hidden-lg">
      <%= image_tag("https://s3-us-west-2.amazonaws.com/climbconnect-assets/backgrounds/cc_chalkbag.jpg", alt: "climb connect home background", class: "img-responsive") %>
      </div>
      <div class="carousel-caption">

        <% unless user_signed_in? %>

        <% if not mobile_app_request? %>
          <%= link_to "Join", new_user_registration_path, class: "btn btn-join btn-lg", data: { turbolinks: false } %>
          <%= link_to "Sign in", new_user_session_path, class: "btn btn-signin btn-lg", data: { turbolinks: false }%>
        <% else %>
          <%= link_to "Join", new_user_registration_path, class: "btn btn-join btn-lg", data: { turbolinks: true } %>
          <%= link_to "Sign in", new_user_session_path, class: "btn btn-signin btn-lg", data: { turbolinks: true }%>
        <% end %>

        <% end %>

      <% if user_signed_in? %>
        <% if FacilityRole.where(email: current_user.email, user_id: nil).count > 0 %>
          <div class="center">
            <p>You have <%= FacilityRole.where(email: current_user.email, user_id: nil).count %> pending <%= "invite".pluralize(FacilityRole.where(email: current_user.email, user_id: nil).count ) %> </p>

          <%= link_to "confirm", inbox_user_path(current_user), class: "btn btn-signin btn-lg", data: { turbolinks: false } %>
          </div>
        <% else %>

        <%= link_to "climb smart", home_user_path(current_user), class: "btn btn-join btn-lg", data: { turbolinks: false } %>
        <%= link_to "set smart", new_admin_facility_path, class: "btn btn-signin btn-lg", data: { turbolinks: false } %>

        <% end %>

      <% end %>


      </div>
    </div>

  </div>
</div>


<div id="features"></div>
<div class="container-fluid">
  <div class="col-sm-7">
    <div class="hero-unit">
        <h1>DISCOVER. TRACK. CONNECT.</h1>
        <h2><i class="fa fa-binoculars" aria-hidden="true"></i> Discover Routes</h2>
        <h2><i class="fa fa-share-alt" aria-hidden="true"></i> Create Circuits</h2>
        <h2><i class="fa fa-bar-chart" aria-hidden="true"></i> Track Progress & Training</h2>
        <h2><i class="fa fa-group" aria-hidden="true"></i> Compete with Friends</h2>
        <br>
        <p>Climb Connect gives you access to the routes your gym is setting and allows you to add your own. Track what you're climbing, set up project lists, and create competitions with your friends. #climbsmart
        </p>
        <% if current_user.present? %>
        <p><%= link_to "Start Today »", new_admin_facility_path, class: "btn btn-blue btn-large pull-right tab", data: { turbolinks: false } %></p>
        <% else %>
        <p><%= link_to "Start Today »", new_user_registration_path, class: "btn btn-blue btn-large pull-right tab", data: { turbolinks: false } %></p>
        <% end %>
        <p><%= link_to "See Demo", admin_facility_path(Facility.where(demo: true).first), class: "btn btn-demo btn-large pull-right", data: { turbolinks: false } %></p>

    </div>
  </div>
  <div class="col-sm-5">
    <br>
    <br>
    <%= image_tag("https://s3-us-west-2.amazonaws.com/climbconnect-assets/photos/cc-climber-female.jpg" ,width: '100%', height: '100%') %>
  </div>
</div>



<div class="container-fluid">
  <br>
  <div class="col-sm-5 hidden-xs">
    <br>
    <%= image_tag("https://s3-us-west-2.amazonaws.com/climbconnect-assets/backgrounds/route-setter.jpg" ,width: '100%', height: '100%') %>
  </div>
  <div class="col-sm-7">
    <div class="hero-unit">
      <h1>Route Setters First</h1>
      <h2><i class="fa fa-wrench" aria-hidden="true"></i> Workflow Optimization</h2>
      <h2><i class="fa fa-group" aria-hidden="true"></i> Team Management</h2>
      <h2><i class="fa fa-area-chart" aria-hidden="true"></i> Facility & Member Analytics</h2>
      <h2><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Custom Grading</h2>
      <br>
      <p>We've worked with some of the best setters in the industry to make sure it creates value in their everyday workflow. It's about staying organized, managing your team, and staying connected. #setsmart
      </p>
        <% if current_user.present? %>
        <p><%= link_to "Start Today »", new_admin_facility_path, class: "btn btn-blue btn-large pull-right tab", data: { turbolinks: false } %></p>
        <% else %>
        <p><%= link_to "Start Today »", new_user_registration_path, class: "btn btn-blue btn-large pull-right tab", data: { turbolinks: false } %></p>
        <% end %>
        <p><%= link_to "See Demo", admin_facility_path(Facility.where(demo: true).first), class: "btn btn-demo btn-large pull-right", data: { turbolinks: false } %></p>
    </div>
  </div>
  <div class="col-xs-12 hidden-sm hidden-md hidden-lg hidden-xl">
    <br>
    <%= image_tag("https://s3-us-west-2.amazonaws.com/climbconnect-assets/backgrounds/route-setter.jpg" ,width: '100%', height: '100%') %>
  </div>
</div>


<div class="container-fluid">
  <div class="col-sm-6">
    <div class="hero-unit">
        <h1>Analytics</h1>
        <p>You don't need an MBA to be an analytics pro.  Show off your work and impress your boss with Climb Connect analytics. #setsmart</p>
        <% if current_user.present? %>
        <p><%= link_to "Start Today »", new_admin_facility_path, class: "btn btn-blue btn-large pull-right tab", data: { turbolinks: false } %></p>
        <% else %>
        <p><%= link_to "Start Today »", new_user_registration_path, class: "btn btn-blue btn-large pull-right tab", data: { turbolinks: false } %></p>
        <% end %>
        <p><%= link_to "See Demo", admin_facility_path(Facility.where(demo: true).first), class: "btn btn-demo btn-large pull-right", data: { turbolinks: false } %></p>
    </div>
  </div>
  <div class="col-sm-6">
    <br>
    <br>
    <%= render 'static_pages/gradedist_boulder' %>
  </div>
</div>


<div class="container-fluid">
  <br>
  <div class="col-sm-5 hidden-xs">
    <br>
    <%= render 'static_pages/route_list' %>
  </div>
  <div class="col-sm-7">
    <div class="hero-unit">
        <h1>Route Database</h1>
        <h2><i class="fa fa-check-circle" aria-hidden="true"></i> Unlimited Storage</h2>
        <h2><i class="fa fa-check-circle" aria-hidden="true"></i> Intuitive User Interface</h2>
        <h2><i class="fa fa-check-circle" aria-hidden="true"></i> Manage and Assign Tasks</h2>
        <h2><i class="fa fa-check-circle" aria-hidden="true"></i> Photos and Video (coming soon!)</h2>
        <br>
        <p>Unlimited storage in a helpful and easy to use database.  Add routes and upload photos from your mobile with only a few taps.  Strip routes and create maintenance tasks based on specific routes. #setsmart </p>

        <% if current_user.present? %>
        <p><%= link_to "Start Today »", new_admin_facility_path, class: "btn btn-blue btn-large pull-right tab", data: { turbolinks: false } %></p>
        <% else %>
        <p><%= link_to "Start Today »", new_user_registration_path, class: "btn btn-blue btn-large pull-right tab", data: { turbolinks: false } %></p>
        <% end %>
        <p><%= link_to "See Demo", admin_facility_path(Facility.where(demo: true).first), class: "btn btn-demo btn-large pull-right", data: { turbolinks: false } %></p>
      </div>
    </div>
    <div class="col-xs-12 hidden-sm hidden-md hidden-lg hidden-xl">
      <br>
      <%= render 'static_pages/route_list' %>
    </div>
  </div>


  <div class="container-fluid">
    <div class="col-sm-8">
      <div class="hero-unit">
          <h1>Customize Your Facility</h1>
          <p>Set up custom grading scales and organize your facility by zones. Create targets and maximize your route setting potential in each area of your gym. #setsmart</p>
          <% if current_user.present? %>
          <p><%= link_to "Start Today »", new_admin_facility_path, class: "btn btn-blue btn-large pull-right tab", data: { turbolinks: false } %></p>
          <% else %>
          <p><%= link_to "Start Today »", new_user_registration_path, class: "btn btn-blue btn-large pull-right tab", data: { turbolinks: false } %></p>
          <% end %>
          <p><%= link_to "See Demo", admin_facility_path(Facility.where(demo: true).first), class: "btn btn-demo btn-large pull-right", data: { turbolinks: false } %></p>
      </div>
    </div>
    <div class="col-sm-4">
      <br>
      <br>
      <%= render 'static_pages/walldist' %>
    </div>

  </div>



<div class="container-fluid">
  <div class="col-sm-6 hidden-xs">
    <br>
    <%= render 'static_pages/task_list' %>
  </div>
  <div class="col-sm-6">
    <div class="hero-unit">
        <h1>Get Things Done</h1>
        <p>Have your day planned before you get out of bed.  Create and assign tasks, manage your team, and stay organize. Strip entire zones and bulk create route setting tasks based on targets that you set. #setsmart</p>
        <% if current_user.present? %>
        <p><%= link_to "Start Today »", new_admin_facility_path, class: "btn btn-blue btn-large pull-right tab", data: { turbolinks: false } %></p>
        <% else %>
        <p><%= link_to "Start Today »", new_user_registration_path, class: "btn btn-blue btn-large pull-right tab", data: { turbolinks: false } %></p>
        <% end %>
        <p><%= link_to "See Demo", admin_facility_path(Facility.where(demo: true).first), class: "btn btn-demo btn-large pull-right", data: { turbolinks: false } %></p>
    </div>
  </div>
  <div class="col-xs-12 hidden-sm hidden-md hidden-lg hidden-xl">
    <br>
    <%= render 'static_pages/task_list' %>
  </div>
</div>


<div class="container-fluid">
  <div class="col-sm-8">
    <div class="hero-unit">
        <h1>Talk to us!</h1>
        <p>We don't wear headsets all day, but we do want to make sure you have everything you need to get set up.  Shoot us an email and we'll respond as quickly as we can to make sure you have what you need.  Or better yet, come climb with us if you're in the Denver area! #setsmart</p>
        <% if current_user.present? %>
        <p><%= link_to "Start Today »", new_admin_facility_path, class: "btn btn-blue btn-large pull-right tab", data: { turbolinks: false } %></p>
        <% else %>
        <p><%= link_to "Start Today »", new_user_registration_path, class: "btn btn-blue btn-large pull-right tab", data: { turbolinks: false } %></p>
        <% end %>
        <p><%= link_to "See Demo", admin_facility_path(Facility.where(demo: true).first), class: "btn btn-demo btn-large pull-right", data: { turbolinks: false } %></p>
        <p><%= mail_to "lee@climbconnect.com", "Say Hello", class: "btn btn-filter btn-large" %></p>
    </div>
  </div>
  <div class="col-sm-4">
    <div class="hidden-xs">
      <br>
      <br>
      <br>
      <br>
    </div>
    <%= image_tag("https://s3-us-west-2.amazonaws.com/climbconnect-assets/backgrounds/Asset+19.png" ,width: '100%', height: '100%') %>
  </div>

</div>
</div>
</div>

app/views/static_pages/marketing.html.erb
<div class="container-fluid hidden-xs">
  <div class="marketing">
    <%= render 'static_pages/marketing' %>
  </div>
</div>

<div class="container-fluid hidden-sm hidden-md hidden-lg hidden-xl">
  <div class="marketing-mobile">
    <%= render 'static_pages/marketing_mobile' %>
  </div>
</div>

app/views/static_pages/pricing.html.erb
<div class="hidden-sm hidden-md hidden-lg hidden-xl"><%= render 'static_pages/marketing_mobile' %></div>
  <div class="hidden-xs">
    <div class="container-fluid">
      <div class="home-body">
        <div class="center jumbotron">

            <h1 id="logo-black">CLIMB | CONNECT<small> BETA</small></h1>
            <h2>Route Management | Facility Analytics | Climb Tracking | January 2017</h2>
            <br/>


          <div class="hidden-xs"><%= render 'static_pages/marketing' %></div>


        </div>
      </div>
    </div>
  </div>