config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  post '/rate' => 'rater#create', :as => 'rate'

  root                  'static_pages#home'
  get 'help'         => 'static_pages#help'
  get 'about'        => 'static_pages#about'
  get 'contact'      => 'static_pages#contact'
  get 'marketing'      => 'static_pages#marketing'
  get 'pricing'      => 'static_pages#pricing'
  get 'privacy_policy'  => 'static_pages#privacy_policy'
  get 'terms_of_service' => 'static_pages#terms_of_service'
  get 'register'     => 'facilities#new'

  resources :users do
    resources :facility_roles
    resources :routes do
      member do
        post :quick_flash #output path - expire_route/:id
        post :quick_redpoint #output path - tagged_route/:id
        post :quick_project
        post :quick_tick
        post :route_like
        post :route_unlike
      end
      collection do
        get :filter_results
        get :index
      end
      resources :ticks
    end
    collection do #collection gets index of users rather than specific tick ID
      get :manage_users
    end
    member do
      get :following, :followers, :competitions, :competition, :new_competition
    end
    member do
      post :follow #output path - user/:id/follow
      post :unfollow #output path - user/:id/unfollow
      get :phone #output path - user/:id/phone
    end

    resources :ticks do
      collection do #collection gets index of ticks rather than specific tick ID
        get :tick_list
      end
    end
    resources :facilities do
      post :unfollow_facility
      post :follow_facility #output path - /users/:user_id/facilities/:facility_id/follow_facility(.:format), user_facility_follow_facility
      resources :routes do
        resources :ticks

      end
    end
    member do
      get :inbox
      get :home
      get :analytics
    end
    resources :competitions do
      member do
        post :invite_user
      end
    end
  end

  resources :facility_roles do
    member do
      post :confirm
    end
  end

  resources :leads

  resources :plans
  resources :charges

  post 'admin/subscriptions/webhook'      => 'admin/subscriptions#webhook' #webhook for Stripe

  resources :relationships,       only: [:create, :destroy]

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :grade_systems do
      resources :grades
    end

    resources :facilities do
      resources :routes do

        member do
          post :expire #output path - expire_route/:id
          post :unexpire
          post :tagged #output path - tagged_route/:id
          post :untagged #output path - tagged_route/:id
          post :create_task
          post :expire_zone_show #expire from zone show page
        end
      end
      resources :subscriptions do
        member do
          post :cancel
        end
      end

      member do
        get :plans
        post :choose_free_plan
        post :choose_basic_plan
        post :choose_pro_plan

      end

      resources :grades
      resources :zones do
        post :mass_expire
        post :mass_create_tasks
      end
      resources :walls
      resources :setters # delete after facility_roles is set up
      resources :facility_roles do
        member do
          post :resend_invite
        end
      end
      resources :sub_child_zones
      resources :facility_grade_systems
      resources :facility_targets
      resources :custom_colors
      resources :tasks do
        member do
          post :activate_route #output path - activate_route/:id
          post :complete_task
          post :uncomplete_task
        end
      end
      resources :competitions do
        member do
          get :routes
          get :route_list
          post :add_route
          post :remove_route
        end
        resources :routes do
          post :add_route
          post :remove_route
        end
      end

    end
  end

  resources :facilities do

    resources :routes, only: [:index, :show]
    resources :grades, only: [:index, :show]
    resources :zones, only: [:index, :show]
    resources :walls, only: [:index, :show]
    resources :setters, only: [:index, :show]
    resources :ticks
    resources :facility_roles
    member do
      post :follow_facility
      post :unfollow_facility
    end
    resources :competitions do
      member do
        get :routes
        get :followers
        get :invite
        get :route_list
        get :results
        post :add_route
        post :remove_route
        post :add_user
      end
      resources :routes do
        post :add_route
        post :remove_route
          member do
            post :quick_flash #output path - expire_route/:id
            post :quick_redpoint #output path - tagged_route/:id
            post :quick_project
            post :quick_comp_flash #output path - expire_route/:id
            post :quick_comp_redpoint #output path - tagged_route/:id
            post :quick_comp_project
            post :quick_tick
          end
      end
    end

    member do
      get :followers
      get :social
      get :analytics
    end
  end

  default_url_options :host => 'localhost:3000'

end

app/models/facility_role.rb
class FacilityRole < ApplicationRecord
  has_many :facilities
  belongs_to :facility
  belongs_to :user

  before_save :downcase_email

  validates :email, presence: true, uniqueness: {scope: [:facility_id]}

  default_scope -> { order("
    CASE
      WHEN facility_roles.name = 'facility_management' THEN '1'
      WHEN facility_roles.name = 'head_setter' THEN '2'
      WHEN facility_roles.name = 'setter' THEN '3'
      WHEN facility_roles.name = 'marketing' THEN '4'
      WHEN facility_roles.name = 'guest' THEN '5'
    END")}

    scope :admin, -> {
    where.not(:name => 'climber')
    }


private

  def self.unconfirmed
    where("confirmed IS NULL OR confirmed = ?", false )
  end


  def downcase_email
    self.email = email.downcase if self.email
  end




end

app/controllers/admin/facility_roles_controller.rb
class Admin::FacilityRolesController < ApplicationController
  before_action :authenticate_user!,        only: [:index, :new, :edit, :update, :destroy], :unless => :facility_is_demo
  before_action :facility_admin,            only: [:index, :edit, :update, :destroy], :unless => :facility_is_demo
  before_action :demo_facility,             except: [:index, :show, :new]
  before_action :setter_role,               except: [:index, :show]
  before_action :guest_role,               except: [:index, :show]
  before_action :marketing_role,            except: [:index, :show]



  include FacilityRolesHelper
  include FacilitiesHelper
  include GradesHelper

  layout "admin"

  def index
    @facility = Facility.find(params[:facility_id])
    @facility_role = FacilityRole.new
    @facility_roles = @facility.facility_roles.admin.includes(:user).page(params[:page]).per(2000)
    @role_names = role_names # populates drop down of role names for creating a new facility user
    @facility_systems = facility_systems.page(params[:page]).per(2000)
  end

  def new
    @facility_role = FacilityRole.new
    @facility = Facility.find(params[:facility_id])
    @facility_roles = @facility.facility_roles.admin.includes(:user).page(params[:page]).per(2000)
    @role_names = role_names
  end

  def create
    @facility = Facility.find(params[:facility_id]) #This ensures the redirect_to goes back to the nested resource
    @facility_role = @facility.facility_roles.build(facility_role_params)
    @facility_roles = @facility.facility_roles.admin.includes(:user).page(params[:page]).per(2000)
    @facility_role.facility_id = params[:facility_id] #this passes the facility ID through the field
    @inviter = current_user
    if @facility_role.save
      flash[:success] = "#{ @facility_role.email } was successfully invited!"
      FacilityRoleMailer.role_invite_email(@facility_role).deliver_now
      redirect_to(admin_facility_facility_roles_path(@facility))
    elsif FacilityRole.where(facility_id: @facility.id, email: @facility_role.email).present?
       @existing_facility_role = FacilityRole.where(facility_id: @facility.id, email: @facility_role.email).first
       @existing_facility_role.update_attributes(name: @facility_role.name)
       flash[:success] = "#{ @existing_facility_role.user.name } was updated to #{ @existing_facility_role.name } !"
       redirect_to(admin_facility_facility_roles_path(@facility))
    else
      flash[:error] = "#{ @facility_role.email } was not added!  Please make sure #{ @facility_role.email } is not already assigned a role."
      redirect_to(admin_facility_facility_roles_path(@facility))
    end
  end

  def update
    @facility = Facility.find(params[:facility_id])
    @facility_role = @facility.facility_roles.find(params[:id])
    if @facility_role.update_attributes(facility_role_params)
      flash[:success] = "Role updated!"
      redirect_to(admin_facility_facility_roles_path(@facility))
      # Handle a successful update.
    else
      render :new
    end
  end

  def edit
    @facility = Facility.find(params[:facility_id])
    @facility_role = FacilityRole.find(params[:id])
    @facility_roles = @facility.facility_roles.admin.includes(:user).page(params[:page]).per(2000)
    @role_names = role_names
  end

  def destroy
    FacilityRole.find(params[:id]).destroy
    flash[:success] = "Role deleted"
    redirect_to :back
  end

  def resend_invite
    @facility_role = FacilityRole.find(params[:id])
    FacilityRoleMailer.role_invite_email(@facility_role).deliver_now
    redirect_to(admin_facility_facility_roles_path(@facility))
  end

  private

    def facility_role_params
      params.require(:facility_role).permit(:email, :name, :user_id, :confirmed, :facility_id)
    end


end

app/controllers/facility_roles_controller.rb
class FacilityRolesController < ApplicationController
  before_action :authenticate_user!


  layout :check_layout

  def check_layout
    if params[:facility_id].present?
      'admin'
    else
      'user'
    end
  end


  include FacilitiesHelper


  def index
    @user = User.find(params[:user_id])
    @facility_role = FacilityRole.new
    @facility_roles = FacilityRole.where(user_id: @user).page(params[:page])

    # put the below in the model eventually ----------
    @userfacilities_check = current_user.facility_relationships.all

        @tick_feed = Tick.where('ticks.created_at > ?', 6.days.ago.to_date).joins(:route).merge(Route.where(facility_id: @userfacilities_check)).includes(:user, :grade, :route, :facility, :rate_average_without_dimension)
        @new_route_feed = Route.where(facility_id: @userfacilities_check).where('routes.created_at > ?', 6.days.ago.to_date).order(created_at: :desc).includes(:zone, :grade, :facility)
        @news_feed = @tick_feed + @new_route_feed
        #newest first
        @news_feed.sort! { |a, b| b.created_at <=> a.created_at }
        @top_10_sends = Tick.includes(:grade, :user).where(route_id: Route.where(facility_id: @userfacilities_check)).ascent.grade_desc.take(10)
        # gets top 10 routes based on ratings cache average
        @top_10_routes = Route.where(facility_id: @userfacilities_check).includes(:grade, :facility, :rating_cache).where(id: RatingCache.where(cacheable_type: "Route").order('rating_caches.avg desc').take(10).map { |rate| [rate.cacheable_id.to_i] } )
        @newest_10_routes = Route.where(facility_id: @userfacilities_check).includes(:grade, :facility, :zone).order('routes.setdate desc').limit(10)
        @ticks = current_user.ticks.where('ticks.date > ?', 7.days.ago.beginning_of_day.to_date)
    # -------------------------------------------------

    @filterrific = initialize_filterrific(
        Facility,
        params[:filterrific],
        select_options: {
          with_state: options_for_state_select,
        },
        persistence_id: false,
      ) or return
      # Get an ActiveRecord::Relation for all students that match the filter settings.
      # You can paginate with will_paginate or kaminari.
      # NOte: filterrific_find returns an ActiveRecord Relation that can be
      # chained with other scopes to further narrow down the scope of the list,
      # e.g., to apply permissions or to hard coded exclude certain types of records.
      @facilities = Facility.filterrific_find(@filterrific).page(params[:page]).per(50)

      # Respond to html for initial page load and to js for AJAX filter updates.
      respond_to do |format|
        format.html
        format.js
      end

    # Recover from invalid param sets, e.g., when a filter refers to the
    # database id of a record that doesn’t exist any more.
    # In this case we reset filterrific and discard all filter params.
    rescue ActiveRecord::RecordNotFound => e
      # There is an issue with the persisted param_set. Reset it.
      puts "Had to reset filterrific params: #{ e.message }"
      redirect_to(reset_filterrific_url(format: :html)) and return
    end



  def show
    @user = User.find(params[:user_id])
  end

  def create
    @user = User.find(params[:user_id])
    @facility_role = @user.facility_roles.build(facility_role_params)
    @facility_roles = FacilityRole.where(user_id: @user).page(params[:page])
    if @facility_role.save
      flash[:success] = "Success!"
      redirect_to(user_facility_roles_path(@user))
    else
      flash[:error] = "#{ @facility_role.email } was not added!  Please make sure #{ @facility_role.email } is not already assigned a role."
      redirect_to(user_facility_roles_path(@user))
    end
  end


  def destroy
    FacilityRole.find(params[:id]).destroy
    redirect_to :back
  end

  def confirm
    @facility_role = FacilityRole.find(params[:id])
    @facility_role.update_attributes(confirmed: true, user_id: current_user.id)
    unless current_user.role == "site_admin"
      current_user.update_attributes(role: "facility_admin")
    end
    redirect_to(inbox_user_path(current_user))
  end

  def new
    @user = current_user
    @facility = Facility.find(params[:facility_id])
    @facility_role = FacilityRole.new

  end




  private

    def facility_role_params
      params.permit(:email, :name, :user_id, :confirmed, :facility_id)
    end

    def options_for_state_select
      us_states
      # provides the list of available grades in the route list filters
    end


end

app/helpers/facility_roles_helper.rb
module FacilityRolesHelper

  def role_names
    [
      ['Facility Management', 'facility_management'],
      ['Head Route Setter', 'head_setter'],
      ['Route Setter', 'setter'],
      ['Marketing/Analytics', 'marketing'],
      ['Guest Setter', 'guest']
    ]
  end


end

app/views/facility_roles/_facility_list.html.erb
<div id="filterrific_facility_results">
  <div class="header bg-top-10">
    <h1>facilities</h1>
  </div>
  <ul>
    <% (@facilities.joins(:facility_roles).group('facilities.id').order('count(facility_roles.user_id) DESC').where('facility_roles.user_id = ?', current_user.id).where(public: true) + @facilities.order('state ASC, city ASC').where(public: true)).uniq.each do |facility| %>
      <%= link_to facility_path(facility) do %>
        <li>
          <p><strong><%= facility.name %></strong>
            <small><%= (" " + facility.location) if facility.location %></small></p>
          <p><small>
            <%= facility.addressline1 if facility.addressline1 %>
            <%= facility.city if facility.city %>
            <%= facility.state if facility.state %>
            <%= facility.zipcode if facility.zipcode %>
          </small></p>
           <br>
          <%= (image_tag(facility.logo_image.url(:medium), class: "img-facility-logo-list-left")) if facility.logo_image%>

          <div class="circle-wrapper">
            <div class="large-circle route-count responsive"><%= facility.routes.current.count %><span class="text"><%= "routes" %></span></div>
          </div>

          <div class="circle-wrapper">
            <div class="large-circle follower-count responsive">
              <% if FacilityRole.where(facility: facility).count > 0 %>
                <%= FacilityRole.where(facility: facility).count %>
              <% else %>
              0
              <% end %>

              <span class="text"><%= "climbers" %></span></div>
          </div>

          <% if FacilityRole.where(facility: facility).where.not(name: 'climber').count == 0 %>

            <%= link_to new_admin_facility_subscription_path(facility) do %>
              <div class="circle-wrapper">
                <div class="large-circle right right-claim responsive"><i class="fa fa-hand-paper-o" aria-hidden="true"></i><span class="text"><%= " claim" %></span></div>
              </div>
            <% end %>

          <% end %>

            <% if FacilityRole.where(user: current_user, facility: facility).where.not(name: 'climber').count > 0 %>

            <%= link_to admin_facility_path(facility) do %>
              <div class="circle-wrapper">
                <div class="large-circle right responsive"><i class="fa fa-dashboard" aria-hidden="true"></i><span class="text"><%= " admin" %></span></div>
              </div>
            <% end %>

            <% elsif FacilityRole.where(user: current_user, facility: facility).where(name: 'climber').count == 0 %>

            <%= link_to user_facility_follow_facility_path(current_user, facility), method: :follow_facility do %>
              <div class="circle-wrapper">
                <div class="large-circle right responsive"><i class="fa fa-plus" aria-hidden="true"></i><span class="text"><%= " follow" %></span></div>
              </div>
            <% end %>

            <% else %>

            <%= link_to user_facility_unfollow_facility_path(current_user, facility), method: :unfollow_facility do %>
              <div class="circle-wrapper">
                <div class="large-circle right green responsive"><i class="fa fa-check" aria-hidden="true"></i><span class="text"><%= " following" %></span></div>
              </div>
            <% end %>

            <% end %>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/facility_roles/_facility_role.html.erb
<br>
<% @facility_roles.each do |f| %>
<ol class="routelist">
  <li style="border: none;">
    <div class="col-sm-12">
      <div class="container-fluid">
        <div class="row">
          <br/>
          <% if f.confirmed? %>
            <% if f.name == 'climber' %>
                <%= link_to facility_path(f.facility_id) do %>

                <div class="col-xs-11 col-sm-11">
                  <div class="row">
                  <h3>
                    <strong><%= f.facility.name %></strong><%= f.facility.location if f.facility.location %>
                  </h3>
                  </div>
                  <div class="row">
                    <p><%= f.name.humanize if f.name %></p>
                  </div>

                </div>
                <% end %>
              <% else %>
              <%= link_to admin_facility_path(f.facility_id) do %>

              <div class="col-xs-11 col-sm-11">
                <div class="row">
                <h3>
                  <strong><%= f.facility.name %></strong><%= f.facility.location if f.facility.location %>
                </h3>
                </div>
                <div class="row">
                  <p><%= f.name.humanize if f.name %></p>
                </div>
              </div>
              <% end %>
            <% end %>
          <% else %>
          <div class="col-xs-11 col-sm-11">
            <div class="row">
              <h3>
                <%= f.email if f.email%>
              </h3>
            </div>
            <div class="row">
              <p><%= f.name.humanize if f.name %></p>
            </div>

          </div>
          <% end %>

          <% if f.name == 'climber' %>
          <div class="col-xs-1 col-sm-1 col-md-1 no-print">
            <h3><%= link_to user_facility_role_path(@user, f),
                        :method => :delete do %>
                        <i class="glyphicon glyphicon-remove"></i>
                        <%end %>
            </h3>
          </div>

          <% end %>
        </div>
      </div>
    </div>
  </li>
</ol>
<% end %>

app/views/facility_roles/_form.html.erb
<div class="container-fluid">
  <div class="row">
    <% if params[:action] == "edit" %>
    <div class="col-sm-12 col-md-6 col-lg-6">
      <br/>
      <label class="hidden-xl">&nbsp;</label>
      <%= @facility_role.email %>
    </div>

    <% else %>

    <div class="col-sm-12">
      <i>Please be sure to use the e-mail the user will sign up with.</i>
      <br/>
      <br/>
      <%= f.label :email, "Recipient's Email Address:" %>
      <%= f.text_field :email, class: 'form-control', placeholder: "Enter email address" %>
    </div>

    <% end %>

    <div class="col-sm-12">
      <%= f.label :name, "Assign role:" %>
      <%= f.select(:name, @role_names ,{include_blank: "Select role..." },{class: "form-control"}) %>
    </div>
  </div>
</div>


<br/>

app/views/facility_roles/_index_partial.html.erb
<div>
  <div class="row">
    <div class="routelist-header bg-blue-gradient">
      <h1><strong>Facilities</strong> </h1>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="top-10 home-stats facility-list left-margin row">
      <%= form_for_filterrific @filterrific do |f| %>
      <div>
        <br>
            <div class="container-fluid">
              <div class="gray-labels">
                <div class="row">
                  <div class="col-xs-12 col-sm-8">
                    <%# give the search field the 'filterrific-periodically-observed' class for live updates %>
                    <div class="form-group">
                      <%= f.text_field(
                        :facility_search_query,
                        placeholder: " Search by name ...",
                        class: 'filterrific-periodically-observed form-control'
                      )%>
                    </div>
                  </div>

                  <div class="col-xs-6 col-sm-4">
                    <%= f.select(
                      :with_state,
                      @filterrific.select_options[:with_state],
                      { include_blank: 'state' },
                      {class: "form-control"}
                    ) %>
                  </div>
                </div>
                <div class="row">
                  <div class="col-xs-12 col-sm-8">
                    <%= link_to "Add new", new_admin_facility_path(@facility) %>
                  </div>
                </div>
              </div>
            </div>
          </div>
      <% end %>
    <%= render 'facility_roles/facility_list', object: @facilities %>
  </div>
  <%= paginate @facilities %>
  </div>
</div>

app/views/facility_roles/_join_facility.html.erb
<div class="col-xs-6 col-sm-3 col-md-3 no-print">
  <div class="row">

<%= form_for [@user, @facility_role], remote: false do |fg| %>
    <div><%= hidden_field_tag :name, 'climber' %></div>
    <div><%= hidden_field_tag :facility_id, f.id %></div>
    <div><%= hidden_field_tag :confirmed, true %></div>
    <div><%= hidden_field_tag :email, @user.email %></div>
    <%= fg.submit "follow", class: "btn btn-add btn-md" %>
<% end %>
  </div>

</div>

app/views/facility_roles/_new_partial.html.erb
Hello

app/views/facility_roles/_unjoin_facility.html.erb
<div class="col-xs-1 col-sm-1 col-md-1 no-print">

  <%= link_to user_facility_roles_path(@user, f), remote: false,
              :method => :delete do %>
              <h3><i class="glyphicon glyphicon-remove"></i></h3>
              <%end %>
</div>

app/views/facility_roles/edit.html.erb
<% provide(:title, 'Facility Team') %>

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12">
      <div class="">
        <h1>Edit team members</h1>
      </div>
      <%= form_for [:admin, @facility, @facility_role], :html => {:class => "form-label"}, remote: false do |f| %>
      <div class="row">
        <%= render 'shared/error_messages', object: f.object %>
      </div>
      <%= render 'admin/facility_roles/form', object: @facility_roles, :f => f %>
      <div class="col-sm-3 col-md-3 col-lg-3">
        <label class="hidden-xl">&nbsp;</label>

        <% if params[:action] == "edit" %>
          <%= f.submit "Save", class: "btn btn-submit" %>
        <% else %>
          <%= f.submit "Send", class: "btn btn-submit" %>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/facility_roles/index.html.erb
<% provide(:title, 'Your Facilities') %>

<div class="container-fluid">
      <div class="row">
        <div class="col-sm-4 hidden-xs">
          <%= render 'users/user_stats', object: @user_tick_feed %>
          <%= render 'users/top10sends', object: @user_tick_feed %>
          <%= render 'users/top10routes', object: @user_tick_feed %>
          <%= render 'users/newest10routes', object: @user_tick_feed %>
        </div>
        <div class="col-sm-8">
            <%= render 'facility_roles/index_partial', object: @user_tick_feed %>
        </div>
      </div>
</div>

app/views/facility_roles/index.js.erb
$("#filterrific_facility_results").html("<%= j (render(partial: 'facility_roles/facility_list', locals: { facilities: @facilities })) %>");

app/views/facility_roles/new.html.erb
<% provide(:title, @facility.name) %>

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12">
      <div class="row">

      </div>
      <div class="row">
        <div class="col-sm-4">
            <%= render 'facilities/facility_stats', object: @facility %>
            <%= render 'facilities/top10sends', object: @facility %>
            <%= render 'facilities/top10routes', object: @facility %>
            <%= render 'facilities/newest10routes', object: @facility %>
        </div>
        <div class="col-sm-8">
          <div class="row">
            <div class="gray-labels routeform-header bg-blue-gradient">
              <h1> NEWS FEED</h1>
            </div>
              <%= render 'facility_roles/new_partial' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/facility_roles/new.js.erb
$('#new_facility_role').hide().after('<%= j render("form") %>')