config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  post '/rate' => 'rater#create', :as => 'rate'

  root                  'static_pages#home'
  get 'help'         => 'static_pages#help'
  get 'about'        => 'static_pages#about'
  get 'contact'      => 'static_pages#contact'
  get 'marketing'      => 'static_pages#marketing'
  get 'pricing'      => 'static_pages#pricing'
  get 'privacy_policy'  => 'static_pages#privacy_policy'
  get 'terms_of_service' => 'static_pages#terms_of_service'
  get 'register'     => 'facilities#new'

  resources :users do
    resources :facility_roles
    resources :routes do
      member do
        post :quick_flash #output path - expire_route/:id
        post :quick_redpoint #output path - tagged_route/:id
        post :quick_project
        post :quick_tick
        post :route_like
        post :route_unlike
      end
      collection do
        get :filter_results
        get :index
      end
      resources :ticks
    end
    collection do #collection gets index of users rather than specific tick ID
      get :manage_users
    end
    member do
      get :following, :followers, :competitions, :competition, :new_competition
    end
    member do
      post :follow #output path - user/:id/follow
      post :unfollow #output path - user/:id/unfollow
      get :phone #output path - user/:id/phone
    end

    resources :ticks do
      collection do #collection gets index of ticks rather than specific tick ID
        get :tick_list
      end
    end
    resources :facilities do
      post :unfollow_facility
      post :follow_facility #output path - /users/:user_id/facilities/:facility_id/follow_facility(.:format), user_facility_follow_facility
      resources :routes do
        resources :ticks

      end
    end
    member do
      get :inbox
      get :home
      get :analytics
    end
    resources :competitions do
      member do
        post :invite_user
      end
    end
  end

  resources :facility_roles do
    member do
      post :confirm
    end
  end

  resources :leads

  resources :plans
  resources :charges

  post 'admin/subscriptions/webhook'      => 'admin/subscriptions#webhook' #webhook for Stripe

  resources :relationships,       only: [:create, :destroy]

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :grade_systems do
      resources :grades
    end

    resources :facilities do
      resources :routes do

        member do
          post :expire #output path - expire_route/:id
          post :unexpire
          post :tagged #output path - tagged_route/:id
          post :untagged #output path - tagged_route/:id
          post :create_task
          post :expire_zone_show #expire from zone show page
        end
      end
      resources :subscriptions do
        member do
          post :cancel
        end
      end

      member do
        get :plans
        post :choose_free_plan
        post :choose_basic_plan
        post :choose_pro_plan

      end

      resources :grades
      resources :zones do
        post :mass_expire
        post :mass_create_tasks
      end
      resources :walls
      resources :setters # delete after facility_roles is set up
      resources :facility_roles do
        member do
          post :resend_invite
        end
      end
      resources :sub_child_zones
      resources :facility_grade_systems
      resources :facility_targets
      resources :custom_colors
      resources :tasks do
        member do
          post :activate_route #output path - activate_route/:id
          post :complete_task
          post :uncomplete_task
        end
      end
      resources :competitions do
        member do
          get :routes
          get :route_list
          post :add_route
          post :remove_route
        end
        resources :routes do
          post :add_route
          post :remove_route
        end
      end

    end
  end

  resources :facilities do

    resources :routes, only: [:index, :show]
    resources :grades, only: [:index, :show]
    resources :zones, only: [:index, :show]
    resources :walls, only: [:index, :show]
    resources :setters, only: [:index, :show]
    resources :ticks
    resources :facility_roles
    member do
      post :follow_facility
      post :unfollow_facility
    end
    resources :competitions do
      member do
        get :routes
        get :followers
        get :invite
        get :route_list
        get :results
        post :add_route
        post :remove_route
        post :add_user
      end
      resources :routes do
        post :add_route
        post :remove_route
          member do
            post :quick_flash #output path - expire_route/:id
            post :quick_redpoint #output path - tagged_route/:id
            post :quick_project
            post :quick_comp_flash #output path - expire_route/:id
            post :quick_comp_redpoint #output path - tagged_route/:id
            post :quick_comp_project
            post :quick_tick
          end
      end
    end

    member do
      get :followers
      get :social
      get :analytics
    end
  end

  default_url_options :host => 'localhost:3000'

end

app/models/competition.rb
class Competition < ApplicationRecord

  belongs_to :facility
  belongs_to :user

  has_many :comp_routes
  has_many :routes, through: :comp_routes, source: :route
  has_many :users_as_participants, :class_name => "CompRelationship"
  has_many :participants, through: :comp_relationships, source: :user
  has_many :comp_relationships

  validates :name, presence: true
  validates :description, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true





  has_attached_file :logo_image, styles: { large: "600", medium: "300", thumb: "100x100#" }, default_url: "https://s3-us-west-2.amazonaws.com/climbconnect-assets/logos/cc-white-block.svg"
  validates_attachment_content_type :logo_image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]


  def self.current
    where('end_date > ?', Date.current).where('end_date > ?', Date.current)
  end

end

app/controllers/admin/competitions_controller.rb
class Admin::CompetitionsController < ApplicationController

  layout "admin"

  include CompetitionsHelper

  def index
    @facility = Facility.find(params[:facility_id])
    @competitions = @facility.competitions.all
  end

  def new
    @competition = Competition.new
    @facility = Facility.find(params[:facility_id])
  end

  def create
    @facility = Facility.find(params[:facility_id]) #This ensures the redirect_to goes back to the nested resource
    @competition = current_user.competitions.build(competition_params)
    @competition.facility_id = params[:facility_id] #this passes the facility ID through the field
    if @competition.save
      flash[:success] = "Competition created!"
      redirect_to(admin_facility_competition_path(@facility, @competition))
    else
      render 'new'
    end
  end

  def edit
    @facility = Facility.find(params[:facility_id])
    @competition = Competition.find(params[:id])
  end

  def update
    @facility = Facility.find(params[:facility_id])
    @competition = Competition.find(params[:id])
    if @competition.update_attributes(competition_params)
      flash[:success] = "Comp updated!"
      redirect_to(admin_facility_competition_path(@facility, @competition))
      # Handle a successful update.
    else
      flash[:error] = "Comp not updaed!  Please check the form."
      redirect_to(edit_admin_facility_competition_path(@facility, @competition))
    end
  end

  def show
    @competition = Competition.find(params[:id])
    @filterrific = initialize_filterrific(
      Route,
      params[:filterrific],
      select_options: {
        sorted_by: Route.options_for_sorted_by,
        with_grade_id: options_for_grade_select,
        with_zone_id: options_for_zone_select,
        with_wall_id: options_for_wall_select,
        with_setter_id: options_for_setter_select,
        with_status_id: Route.options_for_status_select
      },
      persistence_id: false,
    ) or return
    # Get an ActiveRecord::Relation for all students that match the filter settings.
    # You can paginate with will_paginate or kaminari.
    # NOte: filterrific_find returns an ActiveRecord Relation that can be
    # chained with other scopes to further narrow down the scope of the list,
    # e.g., to apply permissions or to hard coded exclude certain types of records.
    @routes = @competition.routes.where(status: nil).filterrific_find(@filterrific).includes(:zone, :wall, :user, :grade ).page(params[:page]).per(50)

    # Respond to html for initial page load and to js for AJAX filter updates.
    respond_to do |format|
      format.html
      format.js
    end

  # Recover from invalid param sets, e.g., when a filter refers to the
  # database id of a record that doesn’t exist any more.
  # In this case we reset filterrific and discard all filter params.
  rescue ActiveRecord::RecordNotFound => e
    # There is an issue with the persisted param_set. Reset it.
    puts "Had to reset filterrific params: #{ e.message }"
    redirect_to(reset_filterrific_url(format: :html)) and return
  end

  def routes
    @facility = Facility.find(params[:facility_id])
    @competition = Competition.find(params[:id])
    @facilityzones = @facility.zones.all.map{|fz| [fz.name, fz.id ] }
    @route_status = route_status_values
    @facility = Facility.find(params[:facility_id])
    @filterrific = initialize_filterrific(
      Route,
      params[:filterrific],
      select_options: {
        sorted_by: Route.options_for_sorted_by,
        with_grade_id: options_for_grade_select,
        with_zone_id: options_for_zone_select,
        with_wall_id: options_for_wall_select,
        with_setter_id: options_for_setter_select,
        with_status_id: Route.options_for_status_select
      },
      persistence_id: false,
    ) or return
    # Get an ActiveRecord::Relation for all students that match the filter settings.
    # You can paginate with will_paginate or kaminari.
    # NOte: filterrific_find returns an ActiveRecord Relation that can be
    # chained with other scopes to further narrow down the scope of the list,
    # e.g., to apply permissions or to hard coded exclude certain types of records.
    @routes = @facility.routes.where(status: nil).filterrific_find(@filterrific).includes(:zone, :wall, :user, :grade ).page(params[:page]).per(50)

    # Respond to html for initial page load and to js for AJAX filter updates.
    respond_to do |format|
      format.html
      format.js
    end

  # Recover from invalid param sets, e.g., when a filter refers to the
  # database id of a record that doesn’t exist any more.
  # In this case we reset filterrific and discard all filter params.
  rescue ActiveRecord::RecordNotFound => e
    # There is an issue with the persisted param_set. Reset it.
    puts "Had to reset filterrific params: #{ e.message }"
    redirect_to(reset_filterrific_url(format: :html)) and return
  end

  def add_route
    @facility = Facility.find(params[:facility_id])
    @competition = Competition.find(params[:id])
    @route = Route.find(params[:route_id])
    @comp_route = CompRoute.new(user_id: current_user.id, route_id: @route.id, competition_id: @competition.id)
    @comp_route.save
    if @comp_route.save
      respond_to do |format|
        format.html {redirect_to @competition}
        format.js
      end
    else
      redirect_to @competition
    end
  end

  def route_list
    @facility = Facility.find(params[:facility_id])
    @competition = Competition.find(params[:id])
    @facilityzones = @facility.zones.all.map{|fz| [fz.name, fz.id ] }
    @route_status = route_status_values
    @facility = Facility.find(params[:facility_id])

    @filterrific = initialize_filterrific(
      Route,
      params[:filterrific],
      select_options: {
        sorted_by: Route.options_for_sorted_by,
        with_grade_id: options_for_grade_select,
        with_zone_id: options_for_zone_select,
        with_wall_id: options_for_wall_select,
        with_setter_id: options_for_setter_select,
        with_status_id: Route.options_for_status_select
      },
      persistence_id: false,
    ) or return
    # Get an ActiveRecord::Relation for all students that match the filter settings.
    # You can paginate with will_paginate or kaminari.
    # NOte: filterrific_find returns an ActiveRecord Relation that can be
    # chained with other scopes to further narrow down the scope of the list,
    # e.g., to apply permissions or to hard coded exclude certain types of records.
    @routes = @competition.routes.where(status: nil).filterrific_find(@filterrific).includes(:zone, :wall, :user, :grade ).page(params[:page]).per(50)

    # Respond to html for initial page load and to js for AJAX filter updates.
    respond_to do |format|
      format.html
      format.js
    end

  # Recover from invalid param sets, e.g., when a filter refers to the
  # database id of a record that doesn’t exist any more.
  # In this case we reset filterrific and discard all filter params.
  rescue ActiveRecord::RecordNotFound => e
    # There is an issue with the persisted param_set. Reset it.
    puts "Had to reset filterrific params: #{ e.message }"
    redirect_to(reset_filterrific_url(format: :html)) and return
  end


#  def add_user
#    @facility = Facility.find(params[:facility_id])
#    @competition = Competition.find(params[:id])
#    @user = current_user
#    @new_participant = CompRelationship.new(user_id: current_user.id, competition_id: @competition.id, role_name: 'climber')
#    @new_participant.save
#    if @new_participant.save
#      respond_to do |format|
#        format.html {redirect_to @competition}
#        format.js
#      end
#    else
#      redirect_to @competition
#    end
#  end



  private

  def competition_params
    params.require(:competition).permit(:user_id, :facility_id, :name, :description, :private, :start_date, :end_date, :private, :password, :password_confirmation, :comp_format, :logo_image)
  end

  def options_for_grade_select
      facility_grades.map{ |sg| [sg.grade, sg.id ] }
    # provides the list of available grades in the route list filters
  end

  def options_for_zone_select
      @facility.zones.all.map{|fz| [fz.name, fz.id ] }
    # provides the list of available zones in the route list filters
  end

  def options_for_wall_select
      @facility.walls.all.map{|fw| [fw.name, fw.id ] }
    # provides the list of available walls in the route list filters
  end

  def options_for_setter_select
      @facility.facility_roles.where(confirmed: true).where.not(name: 'climber').map{|fs| [fs.user.name, fs.user.id]}
    # provides the list of available walls in the route list filters
  end

end

app/helpers/competitions_helper.rb
module CompetitionsHelper
  def comp_formats
    [
      ['Onsight', 'onsight'],
      ['Flash', 'flash'],
      ['Redpoint', 'redpoint'],
      ['Other', 'other'],
    ]
  end

  def false_true
    [
      ['Public', false],
      ['Private', true]
    ]
  end
end

app/views/competitions/_add_to_comp_button.html.erb
<div id="add_route_button_<%= route.id %>">
<% unless CompRoute.find_by(route_id: route.id, competition_id: @competition.id) %>




<%= link_to facility_competition_route_add_route_path(@facility, @competition, route), method: :post, remote: true do %>
<div class="circle-wrapper">
  <div class="comp-add"><i class="fa fa-plus" aria-hidden="true"></i><span class="text"><%= "add" %></span></div>
</div>

<% end %>


<% else %>

<% if CompRoute.find_by(route_id: route.id, competition_id: @competition.id) %>

  <%= link_to facility_competition_route_remove_route_path(@facility, @competition, route), method: :post, remote: true  do %>


  <div class="circle-wrapper">
    <div class="comp-add green-check"><i class="fa fa-check" aria-hidden="true"></i><span class="text"><%= "added" %></span></div>
  </div>

  <% end %>
<% end %>

<% end %>
</div>

app/views/competitions/_comp_user_stats_partial.html.erb
<div id="user-stats" class="center">

  <%= link_to home_user_path(@user) do %>
  <div class="circle-wrapper">
    <div class="large-circle-transparent responsive">
      <% if @user.avatar? %>
        <%= image_tag @user.avatar.url(:medium), class: "img-user-circle-button" %>
      <% elsif @user.image? %>
        <%= image_tag @user.image ,:class=> "img-user-circle-button" %>
      <% else %>
        <%= image_tag @user.avatar.url(:medium), class: "img-user-circle-button" %>
      <% end %>
    </div>
  </div>
  <% end %>

    <%= link_to results_facility_competition_path(@facility, @competition) do %>
      <div class="circle-wrapper">
        <div class="large-circle large-circle-gray responsive">
          <%= Tick.where(competition_id: @competition.id, user_id: current_user.id, tick_type: ['redpoint','flash']).select(:route_id).uniq.count %>
          <span class="text">sends</span></div>
      </div>
    <% end %>


    <%= link_to results_facility_competition_path(@facility, @competition) do %>
      <div class="circle-wrapper">
        <div class="large-circle large-circle-gray responsive">
              <%= Tick.where(competition_id: @competition.id, user_id: current_user.id, tick_type: ['flash']).select(:route_id).uniq.count %>
          <span class="text">flashes</span></div>
      </div>
    <% end %>

    <%= link_to results_facility_competition_path(@facility, @competition) do %>
      <div class="circle-wrapper">
        <div class="large-circle large-circle-gray responsive">
          <%= (Tick.ascent.where(competition_id: @competition.id, user_id: current_user.id).includes(:grade).sum(:rank) + (Tick.where(tick_type: "project", competition_id: @competition.id, user_id: current_user.id).includes(:grade).sum(:rank) * 0.5)).to_i %>
          <span class="text">Try Hard</span></div>
      </div>
    <% end %>


    <%= link_to results_facility_competition_path(@facility, @competition) do %>
      <div class="circle-wrapper">
        <div class="large-circle large-circle-gray responsive">
          <%= top_three_ascent_score(@competition, current_user) %>
          <span class="text">send score</span></div>
      </div>
    <% end %>

    <%= link_to results_facility_competition_path(@facility, @competition) do %>
      <div class="circle-wrapper">
        <div class="large-circle large-circle-gray responsive">
          <%= top_three_flash_score(@competition, current_user) %>
          <span class="text">flash score</span></div>
      </div>
    <% end %>



  </div>

app/views/competitions/_edit_partial.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="routelist-header bg-blue-gradient">
      <h1><strong>Competition</strong>Information</h1>
    </div>
    <br>

    <%= render 'competitions/form', object: @competition %>

  </div>
</div>

<br>

app/views/competitions/_invite_button.html.erb
<div id="comp_invite_button<%= user.id %>" class="circle-wrapper">
  <% if CompInvite.where(invitee_id: user.id, competition_id: @competition.id).count == 0 %>
    <%= link_to invite_user_user_competition_path(user, @competition), method: :post, remote: true do %>
      <div class="">
        <div class="large-circle"><i class="fa fa-plus" aria-hidden="true"></i><span class="text"><%= "invite" %></span></div>
      </div>
    <% end %>
  <% else %>
    <div class="">
      <div class="large-circle green-check"><i class="fa fa-check" aria-hidden="true"></i><span class="text"><%= "invited" %></span></div>
    </div>
  <% end %>



</div>

app/views/competitions/_join_button.html.erb
<div id="comp_join_button">
  <% if @competition.users_as_participants.where(user_id: current_user).count == 0 %>
  <div class='col-sm-3 col-xs-6 comp-stats-center'>
    <span class="comp-stat-icon"><i class="fa fa-plus" aria-hidden="true"></i></span>
    <%= link_to add_user_facility_competition_path(@facility, @competition), method: :post, remote: true do %>
      <div class="comp-circle-wrapper">
        <div class="comp-large-circle responsive"><i class="fa fa-plus" aria-hidden="true"></i><span class="text">Join</span></div>
      </div>
    <% end %>
  </div>
  <% else %>
  <div class='col-sm-3 col-xs-6 comp-stats-center'>
    <span class="comp-stat-icon"><i class="fa fa-check" aria-hidden="true"></i></span>
      <div class="comp-circle-wrapper">
        <div class="comp-large-circle responsive"><i class="fa fa-check" aria-hidden="true"></i><span class="text">You're in!</span></div>
      </div>
  </div>
  <% end %>
</div>

app/views/competitions/_quick_comp_project.html.erb
<div id="quick_project_<%= f.id %>" class="circle-wrapper">


    <%= button_to quick_comp_project_facility_competition_route_path(@facility, @competition, f), method: :post, class: 'btn btn-pretick btn-md', remote: true,
    data: { disable_with:
      "<div class='tick-circle-fill'>
        <i class='fa fa-refresh fa-spin'></i>
      </div>"

    }  do %>
    <% unless Tick.where(competition_id: @competition.id).send_type_count(f, current_user, "project") > 0 %>
      <div class="tick-circle">
    <% else %>
      <div class="tick-circle-fill">
    <% end %>
        <%= Tick.send_type_count(f, current_user, "project") %>
        <span class="text"><%= "attempt".pluralize(Tick.where(competition_id: @competition.id).send_type_count(f, current_user, "project")) %></span>
      </div>
    <% end %>

</div>

app/views/competitions/_results_list_1.html.erb
<script>
      $(function () {
        $('[data-toggle="popover"]').popover()
      })
</script>

<div class="container-fluid bg-dark-gray">

<div class="row left-no-double-margin">

<ol class="resultlist">
  <li>
    <div class="row">

    <div class="col-xs-3">

    </div>
    <div class="col-xs-3">
    <h1>Try Hard Score</h1>
    </div>
    <div class="col-xs-3">
    <h1>Top 3 Score (send)</h1>
    </div>
    <div class="col-xs-3">
    <h1>Top 3 Score (flash)</h1>
    </div>
    <br>
  </div>

  </li>
</ol>


  <% @participants.each do |object| %>
<ol class="resultlist">
  <li>
    <div class="row">
      <div class="col-xs-3">
      <%= object.name %>
      </div>
      <div class="col-xs-3">
        <%= (Tick.ascent.where(competition_id: @competition.id, user_id: object.id).includes(:grade).sum(:rank) + (Tick.where(tick_type: "project", competition_id: @competition.id, user_id: object.id).includes(:grade).sum(:rank) * 0.5)).to_i %>
      </div>
      <div class="col-xs-3">
        <span aria-hidden="true" data-container="body" data-toggle="popover" data-trigger="hover" data-placement="top" data-content="<% Tick.top_three_routes(@competition, object).each do |t| %>
                    <%= t.grade.grade %>
                  <% end %>">
          <%= top_three_ascent_score(@competition, object) %>
        </span>

      </div>
      <div class="col-xs-3">
        <span aria-hidden="true" data-container="body" data-toggle="popover" data-trigger="hover" data-placement="top" data-content="<% Tick.where(tick_type: 'flash').top_three_routes(@competition, object).each do |t| %>
          <%= t.grade.grade %>
          <% end %>">
        <%= top_three_flash_score(@competition, object) %>
        </span>
      </div>
    </div>
  </li>
</ol>
    <% end %>

  </div>
</div>

app/views/competitions/_results_list_2.html.erb
<div class="container-fluid bg-dark-gray">

<div class="row left-no-double-margin">

<ol class="resultlist">
  <li>
    <div class="row">

    <div class="col-xs-3">
    </div>
    <div class="col-xs-2">
    <h1>Routes Sent</h1>
    </div>
    <div class="col-xs-2">
    <h1>Routes Flashed</h1>
    </div>
    <div class="col-xs-2">
    <h1>Send Rate</h1>
    </div>
    <div class="col-xs-2">
    <h1>Flash Rate</h1>
    </div>
    <br>
  </div>

  </li>
</ol>


  <% @participants.each do |object| %>
<ol class="resultlist">
  <li>
    <div class="row">
      <div class="col-xs-3">
      <%= object.name %>
      </div>
      <div class="col-xs-2">
        <%= Tick.where(competition_id: @competition.id, user_id: object.id, tick_type: ['redpoint','flash']).select(:route_id).uniq.count %>
      </div>
      <div class="col-xs-2">
        <%= Tick.where(competition_id: @competition.id, user_id: object.id, tick_type: ['flash']).select(:route_id).uniq.count %>
      </div>
      <div class="col-xs-2">
        <%= number_to_percentage((Tick.where(competition_id: @competition.id, user_id: object.id, tick_type: ['redpoint','flash']).select(:route_id).uniq.count.to_f)/(Tick.where(competition_id: @competition.id, user_id: object.id).select(:route_id).uniq.count.to_f)*100, precision: 0) %>

      </div>
      <div class="col-xs-2">
        <%= number_to_percentage((Tick.where(competition_id: @competition.id, user_id: object.id, tick_type: ['flash']).select(:route_id).uniq.count.to_f)/(Tick.where(competition_id: @competition.id, user_id: object.id).select(:route_id).uniq.count.to_f)*100, precision: 0) %>

      </div>
    </div>
  </li>
</ol>
    <% end %>

  </div>
</div>

app/views/competitions/_routes_partial.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="routelist-header bg-blue-gradient">
      <h1 class="hidden-xs"><strong>Route</strong>Database </h1>
      <h1 class="hidden-sm hidden-md hidden-lg hidden-xl">Routes </h1>
    <span class="pull-right">
      <button class="btn btn-filter" type="button" data-toggle="collapse" data-target="#routeFilters" aria-expanded="false" aria-controls="routeFilters">
        Filters <span class="glyphicon glyphicon-filter"></span>
      </button>
      <% unless params[:controller] == 'admin/competitions' %>
        <span class="hidden-xs"><%= link_to "new route", new_admin_facility_route_path(@facility), class: "btn btn-filter", style: "display: inline-block;" %></span>
      <% end %>
    </span>
  </div>
  </div>
</div>
<%= form_for_filterrific @filterrific do |f| %>

<div class="collapse" id="routeFilters">
  <br>
      <div class="container-fluid bg-routeform">
        <div class="gray-labels">
          <div class="row">
            <div class="col-xs-6 col-sm-5">
              <%= f.label :setdate,  "Set on (start range):" %>
              <%= f.date_field :with_setdate_gte, include_blank: true, class: 'form-control date filterrific-periodically-observed', placeholder: 'mm/dd/yyyy' %>
            </div>
            <div class="col-xs-6 col-sm-5">
              <%= f.label :setdate,  "Set on (end range):" %>
              <%= f.date_field :with_setdate_lt, include_blank: true, class: 'form-control date filterrific-periodically-observed', placeholder: 'mm/dd/yyyy' %>
            </div>
            <div class="col-xs-6 col-sm-2 col-md-2">
              <%= f.label :sorted_by,  "Sort" %>
              <%= f.select(
                :sorted_by,
                @filterrific.select_options[:sorted_by],
                { include_blank: 'Sort by' },
                {class: "form-control"}
              ) %>
            </div>
          </div>
          <div class="row">
            <div class="col-xs-6 col-sm-3">
              <%= f.select(
                :with_grade_id,
                @filterrific.select_options[:with_grade_id],
                { include_blank: 'grades' },
                {class: "form-control"}
              ) %>
            </div>
            <div class="col-xs-6 col-sm-3">
              <%= f.select(
                :with_wall_id,
                @filterrific.select_options[:with_wall_id],
                { include_blank: 'sub-zones' },
                {class: "form-control"}
              ) %>
            </div>
            <div class="col-xs-6 col-sm-3">
              <%= f.select(
                :with_setter_id,
                @filterrific.select_options[:with_setter_id],
                { include_blank: 'setters' },
                {class: "form-control"}
              ) %>
            </div>

          </div>
          <div class="row">
            <div class="col-xs-12">
              <span class="pull-right">
                <%= link_to(
                  'Reset filters',
                  reset_filterrific_url
                ) %>
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>

    <br>

      <div class="row">
        <div class="col-xs-12">
          <div class="route-form">
            <div id="spinner" class="spinner-class hidden" >
              <svg class="spinner" width="65px" height="65px" viewBox="0 0 66 66" xmlns="http://www.w3.org/2000/svg">
               <circle class="path" fill="none" stroke-width="6" stroke-linecap="round" cx="33" cy="33" r="30"></circle>
            </svg>
            </div>
            <div id="donate">
              <% Zone.where(facility_id: @facility).each do |zone| %>
                <label class="purple"><%= f.radio_button :with_zone_id_checkbox, zone.id %>
                  <span><%= zone.name %></span>
                </label>
              <% end %>
              <label class="gray"><%= f.check_box :with_expired_only, {:checked=>true}, Date.current, nil %>
              <span>
                Active only
                </span>
            </label>
              <%= link_to reset_filterrific_url do %>
              <label class="pink">
                <span>Reset</span>
              </label>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <script>
      $(document).bind("ajaxStart", function(){
         $("#spinner").removeClass('hidden');
         $("#donate").addClass('blur-out');
       })

       $(document).bind("ajaxComplete", function(){
         $("#spinner").addClass('hidden');
         $("#donate").removeClass('blur-out');

       });
       </script>


    <% end %>
    <br>


<%= render( 'competitions/route_check_list', routes: @routes )%>

app/views/competitions/followers.html.erb
<% provide(:title, @facility.name + " home") %>

      <div class="row">
        <%= render 'competitions/comp_stats', object: @competition %>
      </div>



      <div class="row">
        <div class="col-sm-12">
      <%= render 'facilities/followers_partial' %>
    </div>
  </div>

app/views/competitions/results.html.erb
<% provide(:title, @facility.name ) %>


          <div class="row">
            <%= render 'competitions/comp_stats', object: @competition %>
          </div>


              <%= render 'competitions/results_partial' %>

app/views/competitions/route_list.html.erb
<% provide(:title, @facility.name ) %>

<div class="row">
  <%= render 'competitions/comp_stats', object: @competition %>
</div>

<br>
<%= render 'competitions/route_list' %>

<script>
$(document).bind("ajaxStart", function(){
   $("#spinner").removeClass('hidden');
   $("#donate").addClass('blur-out');
 })

 $(document).bind("ajaxComplete", function(){
   $("#spinner").addClass('hidden');
   $("#donate").removeClass('blur-out');

 });
 </script>

app/views/competitions/route_list.js.erb
  <% js = escape_javascript(
    render(partial: 'routes/list', locals: { routes: @routes })
  ) %>
  $("#filterrific_results").html("<%= js %>");

app/views/competitions/show.js.erb
  <% js = escape_javascript(
    render(partial: 'competitions/comproute_list', locals: { routes: @routes })
  ) %>
  $("#filterrific_results").html("<%= js %>");