config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  post '/rate' => 'rater#create', :as => 'rate'

  root                  'static_pages#home'
  get 'help'         => 'static_pages#help'
  get 'about'        => 'static_pages#about'
  get 'contact'      => 'static_pages#contact'
  get 'marketing'      => 'static_pages#marketing'
  get 'pricing'      => 'static_pages#pricing'
  get 'privacy_policy'  => 'static_pages#privacy_policy'
  get 'terms_of_service' => 'static_pages#terms_of_service'
  get 'register'     => 'facilities#new'

  resources :users do
    resources :facility_roles
    resources :routes do
      member do
        post :quick_flash #output path - expire_route/:id
        post :quick_redpoint #output path - tagged_route/:id
        post :quick_project
        post :quick_tick
        post :route_like
        post :route_unlike
      end
      collection do
        get :filter_results
        get :index
      end
      resources :ticks
    end
    collection do #collection gets index of users rather than specific tick ID
      get :manage_users
    end
    member do
      get :following, :followers, :competitions, :competition, :new_competition
    end
    member do
      post :follow #output path - user/:id/follow
      post :unfollow #output path - user/:id/unfollow
      get :phone #output path - user/:id/phone
    end

    resources :ticks do
      collection do #collection gets index of ticks rather than specific tick ID
        get :tick_list
      end
    end
    resources :facilities do
      post :unfollow_facility
      post :follow_facility #output path - /users/:user_id/facilities/:facility_id/follow_facility(.:format), user_facility_follow_facility
      resources :routes do
        resources :ticks

      end
    end
    member do
      get :inbox
      get :home
      get :analytics
    end
    resources :competitions do
      member do
        post :invite_user
      end
    end
  end

  resources :facility_roles do
    member do
      post :confirm
    end
  end

  resources :leads

  resources :plans
  resources :charges

  post 'admin/subscriptions/webhook'      => 'admin/subscriptions#webhook' #webhook for Stripe

  resources :relationships,       only: [:create, :destroy]

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :grade_systems do
      resources :grades
    end

    resources :facilities do
      resources :routes do

        member do
          post :expire #output path - expire_route/:id
          post :unexpire
          post :tagged #output path - tagged_route/:id
          post :untagged #output path - tagged_route/:id
          post :create_task
          post :expire_zone_show #expire from zone show page
        end
      end
      resources :subscriptions do
        member do
          post :cancel
        end
      end

      member do
        get :plans
        post :choose_free_plan
        post :choose_basic_plan
        post :choose_pro_plan

      end

      resources :grades
      resources :zones do
        post :mass_expire
        post :mass_create_tasks
      end
      resources :walls
      resources :setters # delete after facility_roles is set up
      resources :facility_roles do
        member do
          post :resend_invite
        end
      end
      resources :sub_child_zones
      resources :facility_grade_systems
      resources :facility_targets
      resources :custom_colors
      resources :tasks do
        member do
          post :activate_route #output path - activate_route/:id
          post :complete_task
          post :uncomplete_task
        end
      end
      resources :competitions do
        member do
          get :routes
          get :route_list
          post :add_route
          post :remove_route
        end
        resources :routes do
          post :add_route
          post :remove_route
        end
      end

    end
  end

  resources :facilities do

    resources :routes, only: [:index, :show]
    resources :grades, only: [:index, :show]
    resources :zones, only: [:index, :show]
    resources :walls, only: [:index, :show]
    resources :setters, only: [:index, :show]
    resources :ticks
    resources :facility_roles
    member do
      post :follow_facility
      post :unfollow_facility
    end
    resources :competitions do
      member do
        get :routes
        get :followers
        get :invite
        get :route_list
        get :results
        post :add_route
        post :remove_route
        post :add_user
      end
      resources :routes do
        post :add_route
        post :remove_route
          member do
            post :quick_flash #output path - expire_route/:id
            post :quick_redpoint #output path - tagged_route/:id
            post :quick_project
            post :quick_comp_flash #output path - expire_route/:id
            post :quick_comp_redpoint #output path - tagged_route/:id
            post :quick_comp_project
            post :quick_tick
          end
      end
    end

    member do
      get :followers
      get :social
      get :analytics
    end
  end

  default_url_options :host => 'localhost:3000'

end

app/models/facility_target.rb
class FacilityTarget < ApplicationRecord
  belongs_to :facility
  belongs_to :grade
  belongs_to :zone
  belongs_to :wall
  belongs_to :sub_child_zone
  belongs_to :user
  has_many :grades

  validates :value, presence: true
  validates :zone_id, uniqueness: {scope: [:grade_id, :wall_id, :sub_child_zone_id]}
  validates :wall_id, uniqueness: {scope: [:zone_id, :sub_child_zone_id, :grade_id]}
  validates :sub_child_zone_id, uniqueness: {scope: [:zone_id, :wall_id, :grade_id]}
  validates :grade_id, presence: true, uniqueness: {scope: [:zone_id, :wall_id, :sub_child_zone_id]}

  default_scope -> { order(created_at: :desc) }


end

app/controllers/admin/facility_targets_controller.rb
class Admin::FacilityTargetsController < ApplicationController
    before_action :authenticate_user!,        only: [:index, :show, :new, :create, :edit, :update, :destroy], :unless => :facility_is_demo
    before_action :facility_admin,            only: [:index, :show, :new, :create, :edit, :update, :destroy], :unless => :facility_is_demo
    before_action :demo_facility,             except: [:index, :show, :new]
    before_action :setter_role,               only: [:destroy], :unless => :facility_is_demo
    before_action :guest_role,                only: [:index, :show, :new, :create, :edit, :update, :destroy], :unless => :facility_is_demo
    before_action :marketing_role,            except: [:index, :show], :unless => :facility_is_demo


    include FacilityTargetsHelper

    layout 'admin'

    def index
      @facility_target = FacilityTarget.new
      @facility_targets = @facility.facility_targets.page(params[:page]).per(500)
      @facility = Facility.find(params[:facility_id])
      @facilityzones = @facility.zones.all.map{|fz| [fz.name, fz.id ] }
      @facilitywalls = @facility.walls.all.map{|fw| [fw.name, fw.id ] }
    end


    def new
      @facility_target = FacilityTarget.new
      @facility = Facility.find(params[:facility_id])
      @facilityzones = @facility.zones.all.map{|fz| [fz.name, fz.id ] }
      @facilitygrades = facility_grades.map{ |sg| [sg.grade, sg.id ] }
      @facilitywalls = @facility.walls.all.map{|fw| [fw.name, fw.id ] }
      @facilitysubchildzones = @facility.sub_child_zones.all.map{|fw| [fw.name, fw.id ] }
      @facilitysetters = @facility.facility_roles.where(confirmed: true).map{|fs| [fs.user.name, fs.user.id]}
      @recentfacility_targets = @facility.facility_targets.order("created_at DESC").page(params[:page]).limit(10)
    end

    def show
      @facility_target = FacilityTarget.find(params[:id])
      @facility = Facility.find(params[:facility_id])
      @totalticks = Tick.where("facility_target_id = ?", @facility_target)
      @averagerating = Rate.where("rateable_id = ?", @facility_target).average(:stars)
      @ratingcount = Rate.where("rateable_id = ?", @facility_target).count(:stars)
    end

    def create
      @facility = Facility.find(params[:facility_id])
      @facility_target = current_user.facility_targets.build(facility_target_params)
      @facility_targets = @facility.facility_targets.page(params[:page]).per(500)
      @facilityzones = @facility.zones.all.map{|fz| [fz.name, fz.id ] }

      @facilitygrades = facility_grades.map{ |sg| [sg.grade, sg.id ] }

      @facilitywalls = @facility.walls.all.map{|fw| [fw.name, fw.id ] }
      @facilitysetters = @facility.facility_roles.where(confirmed: true).map{|fs| [fs.user.name, fs.user.id]}
      @recentfacility_targets = @facility.facility_targets.order("created_at DESC").page(params[:page]).limit(10)
      @facility_target.facility_id = params[:facility_id]
      if @facility_target.save
        respond_to do |format|
          format.html { redirect_to(admin_facility_facility_targets_path(@facility)) }
          format.js
        end
      else
        render 'index'
      end
    end

    def edit
      @facility = Facility.find(params[:facility_id])
      @facility_target = FacilityTarget.find(params[:id])
      @facilityzones = @facility.zones.all.map{|fz| [fz.name, fz.id ] }

      @facilitygrades = facility_grades.map{ |sg| [sg.grade, sg.id ] }

      @facilitywalls = @facility.walls.all.map{|fw| [fw.name, fw.id ] }
      @facilitysetters = @facility.facility_roles.where(confirmed: true).map{|fs| [fs.user.name, fs.user.id]}
      @facility_target.facility_id = params[:facility_id]
      @recentfacility_targets = @facility.facility_targets.order("created_at DESC").page(params[:page]).limit(10)

      @facilitydisciplines = facility_grades.map{ |fg| [fg.discipline, fg.discipline ] }

    end

    def update
      @facility = Facility.find(params[:facility_id])
      @facility_target = FacilityTarget.find(params[:id])
      @facility_targets = @facility.facility_targets.page(params[:page]).per(500)
      if @facility_target.update_attributes(facility_target_params)
        flash[:success] = "Route updated"
        redirect_to(admin_facility_facility_targets_path(@facility))
        # Handle a successful update.
      else
        render 'index'
      end
    end


    def destroy
      @facility_target = FacilityTarget.find(params[:id])
      if @facility_target.delete
        respond_to do |format|
          format.html { redirect_to :back }
          format.js
        end
      end
    end

    private


    def facility_target_params
      params.require(:facility_target).permit(:value, :facility_id, :grade_id, :zone_id, :wall_id, :sub_child_zone_id, :user_id)
    end
end

app/helpers/facility_targets_helper.rb
module FacilityTargetsHelper

  def facility_systems
    GradeSystem.joins(:facilities).where(:facilities => {:id => @facility.id})
  end

# Joins grades to facilities via grade_system and facility_grade_system relationships
  def facility_grades
    Grade.joins(:facilities).where(:facilities => {:id => @facility.id} )
  end

  def facility_systems_route_count
    facility_grades.joins(:routes).where(:routes => {:grade_id => facility_grades.id} ).size
  end

end

app/views/admin/facility_targets/_facility_targets.html.erb
<ol class="routelist">
<% @facility_targets.each do |f| %>


  <li style="border: none;">
    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-6 col-sm-8">

          <span><h3><%= f.grade.grade if f.grade %> <%= f.zone.name if f.zone %></h3></span>
        </div>
        <div class="col-xs-6 col-sm-3">
            <div class="circle pull-right"><%= f.value %></div>
        </div>

        <div class="col-xs-1 col-sm-1 col-md-1">
          <h3><%= link_to admin_facility_facility_target_path(@facility, f), data: {:confirm => 'Are you sure? This cannot be undone.'},
                      :method => :delete, remote: true do %>
                      <i class="glyphicon glyphicon-trash pull-right"></i>
                      <%end %>
          </h3>
        </div>

      </div>
        <div class="row">
          <div class="col-xs-12">
            <strong>System: </strong><%= f.grade.grade_system.name %>
          </div>
          <br>
          <br>
      </div>
  </li>

<% end %>
</ol>

app/views/admin/facility_targets/_form.html.erb
<br/>
<div class="gray-labels">
<div class="container-fluid bg-routeform">
    <%= form_for [:admin, @facility, @facility_target ], :html => {:id => "targetForm"}, remote: true  do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

    <div class="row">
      <div class="col-sm-3">
        <%= f.label :grade_id,"Grade*" %>
        <%= f.grouped_collection_select(:grade_id, facility_systems , :grades, :name, :id, :grade,
        { include_blank: 'Select grade' },
        {class: "form-control"}) %>
      </div>
      <div class="col-sm-3">
        <%= f.label :zone_id,"Zone*" %>
        <%= f.select(:zone_id, @facilityzones,
        { include_blank: 'Select primary zone' },
        {class: "form-control"}) %>
      </div>
      <div class="col-sm-3">
        <%= f.label :value, "Target value*" %>
        <%= f.text_field :value, class: 'form-control', placeholder: "Number of routes..." %>
      </div>
      <div class="col-sm-3">
        <%= f.label "Submit" %>
        <%= f.submit "Save", class: "btn btn-save btn-lg" %>
      </div>
    </div>



</div>
</div>
<% end %>
<br/>

app/views/admin/facility_targets/create.js.erb
<% js = escape_javascript(
  render(partial: 'admin/facility_targets/facility_targets', locals: { object: @facility_targets })
) %>
$("#facility_targets").html("<%= js %>");
$('#targetForm')[0].reset();

app/views/admin/facility_targets/destroy.js.erb
<% js = escape_javascript(
  render(partial: 'admin/facility_targets/facility_targets', locals: { object: @facility_targets })) %>
  $("#facility_targets").html("<%= js %>");

app/views/admin/facility_targets/edit.html.erb
<% provide(:title, 'Facility Targets') %>

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12">
      <div class="">
        <h1>Edit target</h1>
        <br/>
        <i>Targets will be used to indicate if you are
        above or below your desired route count.</i>
      </div>
        <%= render 'admin/facility_targets/form', object: @facility_targets %>
    </div>
  </div>

app/views/admin/facility_targets/index.html.erb
<% provide(:title, 'Facility Targets') %>

<div class="container-fluid">
  <div class="row">
      <div class="routelist-header bg-blue-gradient">
        <h1 class="hidden-xs"><strong>Facility</strong>Targets </h1>
      </div>
    </div>
    <div class="row">
        <br>
        <i>Targets will be used to indicate if you are
        above or below your desired route count.</i>
        <%= render 'admin/facility_targets/form', object: @facility_targets %>
        <br/>
        <div id="facility_targets">
          <div class="col-sm-12">
            <div class="row">
              <%= render 'admin/facility_targets/facility_targets', object: @facility_targets %>
            </div>
          </div>
        </div>
    </div>
</div>